config/routes.rb
DemoJquery::Application.routes.draw do
  resources :articles do
    resources :posts  
  end

  
root :to => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  #accepts_nested_attributes_for :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :article
  #accepts_nested_attributes_for :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :except => [:create]
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  respond_to :js #, :only => [:create, :destroy]
  belongs_to :article
  #def create
  #  create! {}
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'All articles', articles_path %> |
<%= link_to 'View posts', article_posts_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoJquery</title>
  <%= stylesheet_link_tag 'application' %>
  <%#= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery.min', 'jquery-ui.min', 'jquery_ujs', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<%#= link_to 'Article', articles_path %> 
<%#= link_to 'Post', article_posts_path %>
<%= yield %>

<div id="footer" style="margin-top: 200px; height: 100px; text-align: center;">
  <span style="text-align: center;"> contact to kevin@vinova.sg </span>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%#= form_for(params[:article_id], @post, :remote => true) do |f| %>
<%#= form_for [@article, Post.new], :remote => true) do |f| %>
 <%#= @article.inspect %>
<%#= @post.inspect %>
<%= form_for([@article, Post.new], :remote => true) do |f| %>  
  <%#= form_authenticity_token %>
 
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%#= f.input :content %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :rows => 10  %>
    <%#= f.input :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post"%>
    <%#= f.button, :submit%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= content_tag_for(:li, post) do %>
  <p><b><%= post.name %></b> says that: </p>
  <p><%= post.content %></p>
  <span class="age">Posted at <%= time_ago_in_words(post.created_at) %> ago.
  (<%= link_to 'Delete', article_post_path(@article, post), :confirm => 'Are you sure?', :method => :delete, :remote => true %>)</span>
<% end %>

app/views/posts/create.js.erb
$('#posts').prepend('<%= escape_javascript(render(@post)) %>');
$('#posts > li:first').effect('highlight', {}, 3000);
$('#post_form > form')[0].reset();

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post) %>').css('background', 'red');
$('#<%= dom_id(@post) %>').hide("fade", {}, 1500);

app/views/posts/index.html.erb
<h1>Posts for <b><%= @article.title %></b></h1>
<%= link_to 'Back to articles', articles_path %>
<br/>
<div id="post_form">
  <%= render :partial => 'form' %>
</div>

<ul id="posts">
  <%= render :partial => @posts.reverse %>
</ul>